base_url = "https://testingapollo.vercel.app"
title = "nune's site"
description = "This is an example description"
build_search_index = false
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle"              # light, dark, auto, toggle
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true
repo_url = "https://github.com/not-matthias/apollo/tree/main/content"

menu = [
    { name = "index", url = "/", weight = 1 },
    { name = "services", url = "/services", weight = 2 },
    { name = "collection", url = "/collection", weight = 3 },
    { name = "other", url = "/tags", weight = 4 },
]

socials = [
    { name = "instagram", url = "https://instagram.com/blitzw.in", icon = "instagram" },
]

custom_css = []

[extra.analytics]
enabled = false

[extra.analytics.goatcounter]
user = "your_user"
host = "example.com" # default= goatcounter.com

[extra.analytics.umami]
website_id = "43929cd1-1e83...."
host_url = "https://stats.mywebsite.com" # default: https://analytics.eu.umami.is
